#!/bin/bash

# This utility script will build the HCPprocessPipelinesSandbox for testing changes
# based on the HCPprocessPipelines.img file that has already been created from
# the HCPprocessPipelines recipe file.
#
# This assumes you have sudoer privileges on the system on which you are trying to
# build the sandbox.

if [ -e "HCPprocessPipelinesSandbox" ]; then
	sudo rm -rf HCPprocessPipelinesSandbox
fi

if [ -f "HCPprocessPipelines.img" ]; then
	time sudo singularity build --sandbox HCPprocessPipelinesSandbox/ HCPprocessPipelines.img
else
	echo "ERROR: The sandbox cannot be built from the container image because the container image doesn't exist."
	echo "ERROR: Use build_container first to build the container image."
fi
