#!/bin/bash

# This utility script will build the HCPprocessPipelines.simg container
# from the HCPprocessPipelinesSandbox/
#
# This assumes you have sudoer privileges on the system on which you are trying to
# build the sandbox.

if [ -e "HCPprocessPipelinesSandbox" ]; then
	time sudo singularity build HCPprocessPipelines.simg HCPprocessPipelinesSandbox/
else
	echo "ERROR - HCPprocessPipelinesSandbox does not exist"
	exit 1
fi
