#!/bin/bash

# This utility script will build the HCPprocessPipelinesSandbox from the
# HCPprocessPipelines Singularity recipe file
#
# This assumes you have sudoer privileges on the system on which you are trying to
# build the sandbox.

if [ -e "HCPprocessPipelinesSandbox" ]; then
	sudo rm -rf HCPprocessPipelinesSandbox
fi

time sudo singularity build --sandbox HCPprocessPipelinesSandbox/ HCPprocessPipelines

